# Generated by Django 6.0.1 on 2026-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_salarypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypayment',
            name='month',
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='title',
            field=models.CharField(default='Salary Payment', max_length=255),
        ),
    ]
