# Generated by Django 6.0.1 on 2026-01-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_salarypayment_month_salarypayment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Housing', 'Housing'), ('Salary', 'Salary'), ('Liability', 'Debt Repayment'), ('Other', 'Other')], max_length=50),
        ),
    ]
