# Generated by Django 6.0.1 on 2026-01-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_project_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
