# Generated by Django 6.0.1 on 2026-01-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_is_project_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advance_income_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_advance', to='api.income'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='income_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment', to='api.income'),
        ),
    ]
